import type { Metadata } from "next";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/lib/Providers/Providers";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   
      <html lang="en">
     <Providers>
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <>
          <Toaster position="top-center"/>
          {children}
          </>
        </AppRouterCacheProvider>
      </body>
       </Providers>
    </html>
    
  );
}
